<a href="https://colab.research.google.com/github/hhurchand/MLProject/blob/master/Projet_COVID_FV2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd 
from scipy.integrate import odeint
from sklearn.tree import DecisionTreeClassifier



In [ ]:
df = pd.read_csv('Data_KNN_finalV2.csv')
df.head(5)

Unnamed: 0      id  sex  patient_type  entry_date date_symptoms  \
0           0  16169f    2             1  04-05-2020    02-05-2020   
1           1  1009bf    2             1  19-03-2020    17-03-2020   
2           2  167386    1             2  06-04-2020    01-04-2020   
3           3  0b5948    2             2  17-04-2020    10-04-2020   
4           4  0d01b5    1             2  13-04-2020    13-04-2020   

    date_died  intubed  pneumonia  age  ...  obesity  renal_chronic  tobacco  \
0           0        3        2.0   27  ...      2.0            2.0      2.0   
1           0        3        2.0   24  ...      2.0            2.0      2.0   
2           0        2        2.0   54  ...      1.0            2.0      2.0   
3           0        2        1.0   30  ...      2.0            2.0      2.0   
4  22-04-2020        2        2.0   60  ...      2.0            2.0      2.0   

   contact_other_covid  covid_res  icu  age_group  age_group2  survived  \
0                    2          1    2      21-30          30         1   
1                    1          1    2      21-30          30         1   
2                    1          1    2      41-60          60         1   
3                    1          1    2      21-30          30         1   
4                    1          1    2      41-60          60         0   

   wait_time  
0          2  
1          2  
2          5  
3          7  
4          0  

[5 rows x 28 columns]

In [ ]:
df.describe()

Unnamed: 0            sex   patient_type        intubed  \
count  566602.000000  566602.000000  566602.000000  566602.000000   
mean   283300.500000       1.506726       1.215165       2.767248   
std    163564.052948       0.499955       0.410937       0.462335   
min         0.000000       1.000000       1.000000       1.000000   
25%    141650.250000       1.000000       1.000000       3.000000   
50%    283300.500000       2.000000       1.000000       3.000000   
75%    424950.750000       2.000000       1.000000       3.000000   
max    566601.000000       2.000000       2.000000       3.000000   

           pneumonia            age      pregnancy       diabetes  \
count  566602.000000  566602.000000  566602.000000  566602.000000   
mean        1.844379      42.622483       2.499555       1.874472   
std         0.362496      16.659973       0.514142       0.330977   
min         1.000000       0.000000       1.000000       1.000000   
25%         2.000000      31.000000       2.000000       2.000000   
50%         2.000000      41.000000       3.000000       2.000000   
75%         2.000000      53.000000       3.000000       2.000000   
max         2.000000     120.000000       3.000000       2.000000   

                copd         asthma  ...  cardiovascular        obesity  \
count  566602.000000  566602.000000  ...   566602.000000  566602.000000   
mean        1.983854       1.968175  ...        1.977415       1.836940   
std         0.125980       0.175524  ...        0.148523       0.369314   
min         1.000000       1.000000  ...        1.000000       1.000000   
25%         2.000000       2.000000  ...        2.000000       2.000000   
50%         2.000000       2.000000  ...        2.000000       2.000000   
75%         2.000000       2.000000  ...        2.000000       2.000000   
max         2.000000       2.000000  ...        2.000000       2.000000   

       renal_chronic        tobacco  contact_other_covid      covid_res  \
count  566602.000000  566602.000000        566602.000000  566602.000000   
mean        1.980124       1.915149             1.631336       1.728651   
std         0.139538       0.278575             0.751383       0.658710   
min         1.000000       1.000000             1.000000       1.000000   
25%         2.000000       2.000000             1.000000       1.000000   
50%         2.000000       2.000000             1.000000       2.000000   
75%         2.000000       2.000000             2.000000       2.000000   
max         2.000000       2.000000             3.000000       3.000000   

                 icu     age_group2       survived      wait_time  
count  566602.000000  566602.000000  566602.000000  566602.000000  
mean        1.982153      48.971183       0.936153       3.665589  
std         0.132394      17.370880       0.244481       3.280740  
min         1.000000       3.000000       0.000000       0.000000  
25%         2.000000      40.000000       1.000000       1.000000  
50%         2.000000      60.000000       1.000000       3.000000  
75%         2.000000      60.000000       1.000000       5.000000  
max         2.000000      80.000000       1.000000     115.000000  

[8 rows x 23 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 566602 entries, 0 to 566601
Data columns (total 28 columns):
 #   Column               Non-Null Count   Dtype  
---  ------               --------------   -----  
 0   Unnamed: 0           566602 non-null  int64  
 1   id                   566602 non-null  object 
 2   sex                  566602 non-null  int64  
 3   patient_type         566602 non-null  int64  
 4   entry_date           566602 non-null  object 
 5   date_symptoms        566602 non-null  object 
 6   date_died            566602 non-null  object 
 7   intubed              566602 non-null  int64  
 8   pneumonia            566602 non-null  float64
 9   age                  566602 non-null  int64  
 10  pregnancy            566602 non-null  int64  
 11  diabetes             566602 non-null  float64
 12  copd                 566602 non-null  float64
 13  asthma               566602 non-null  float64
 14  inmsupr              566602 non-null  float64
 15  hypertension     

In [ ]:
df.columns

Index(['Unnamed: 0', 'id', 'sex', 'patient_type', 'entry_date',
       'date_symptoms', 'date_died', 'intubed', 'pneumonia', 'age',
       'pregnancy', 'diabetes', 'copd', 'asthma', 'inmsupr', 'hypertension',
       'other_disease', 'cardiovascular', 'obesity', 'renal_chronic',
       'tobacco', 'contact_other_covid', 'covid_res', 'icu', 'age_group',
       'age_group2', 'survived', 'wait_time'],
      dtype='object')

In [ ]:
df.describe()

Unnamed: 0            sex   patient_type        intubed  \
count  566602.000000  566602.000000  566602.000000  566602.000000   
mean   283300.500000       1.506726       1.215165       2.767248   
std    163564.052948       0.499955       0.410937       0.462335   
min         0.000000       1.000000       1.000000       1.000000   
25%    141650.250000       1.000000       1.000000       3.000000   
50%    283300.500000       2.000000       1.000000       3.000000   
75%    424950.750000       2.000000       1.000000       3.000000   
max    566601.000000       2.000000       2.000000       3.000000   

           pneumonia            age      pregnancy       diabetes  \
count  566602.000000  566602.000000  566602.000000  566602.000000   
mean        1.844379      42.622483       2.499555       1.874472   
std         0.362496      16.659973       0.514142       0.330977   
min         1.000000       0.000000       1.000000       1.000000   
25%         2.000000      31.000000       2.000000       2.000000   
50%         2.000000      41.000000       3.000000       2.000000   
75%         2.000000      53.000000       3.000000       2.000000   
max         2.000000     120.000000       3.000000       2.000000   

                copd         asthma  ...  cardiovascular        obesity  \
count  566602.000000  566602.000000  ...   566602.000000  566602.000000   
mean        1.983854       1.968175  ...        1.977415       1.836940   
std         0.125980       0.175524  ...        0.148523       0.369314   
min         1.000000       1.000000  ...        1.000000       1.000000   
25%         2.000000       2.000000  ...        2.000000       2.000000   
50%         2.000000       2.000000  ...        2.000000       2.000000   
75%         2.000000       2.000000  ...        2.000000       2.000000   
max         2.000000       2.000000  ...        2.000000       2.000000   

       renal_chronic        tobacco  contact_other_covid      covid_res  \
count  566602.000000  566602.000000        566602.000000  566602.000000   
mean        1.980124       1.915149             1.631336       1.728651   
std         0.139538       0.278575             0.751383       0.658710   
min         1.000000       1.000000             1.000000       1.000000   
25%         2.000000       2.000000             1.000000       1.000000   
50%         2.000000       2.000000             1.000000       2.000000   
75%         2.000000       2.000000             2.000000       2.000000   
max         2.000000       2.000000             3.000000       3.000000   

                 icu     age_group2       survived      wait_time  
count  566602.000000  566602.000000  566602.000000  566602.000000  
mean        1.982153      48.971183       0.936153       3.665589  
std         0.132394      17.370880       0.244481       3.280740  
min         1.000000       3.000000       0.000000       0.000000  
25%         2.000000      40.000000       1.000000       1.000000  
50%         2.000000      60.000000       1.000000       3.000000  
75%         2.000000      60.000000       1.000000       5.000000  
max         2.000000      80.000000       1.000000     115.000000  

[8 rows x 23 columns]

In [ ]:
# Vérifions si nous avons des valeurs null : 
df.isnull().any()

Unnamed: 0             False
id                     False
sex                    False
patient_type           False
entry_date             False
date_symptoms          False
date_died              False
intubed                False
pneumonia              False
age                    False
pregnancy              False
diabetes               False
copd                   False
asthma                 False
inmsupr                False
hypertension           False
other_disease          False
cardiovascular         False
obesity                False
renal_chronic          False
tobacco                False
contact_other_covid    False
covid_res              False
icu                    False
age_group              False
age_group2             False
survived               False
wait_time              False
dtype: bool

In [ ]:
df['icu'].unique()
#1	SI : Yes
#2	NO : No
#97	NO APLICA : DOES NOT APPLY
#98	SE IGNORA : IT IS IGNORED
#99	NO ESPECIFICADO : NO ESPECIFICADO


array([2, 1], dtype=int64)

In [ ]:
df['icu']=df['icu'].replace('11bc25', 'nan')
df['icu'].dropna()

0         2
1         2
2         2
3         2
4         2
         ..
566597    2
566598    2
566599    2
566600    2
566601    2
Name: icu, Length: 566602, dtype: int64

In [ ]:
df['icu']=df['icu'].replace(97, 2)
df['icu']=df['icu'].replace(99, 2)
df['icu'].unique()

## nous avons remplacer les autres catégorie par 2 pour garder que icu = 1 et icu = 2 afin 
##de determiner les cas susceptible d'aller dans les soins intensifs.
## Vu que les autres catégories sont non applicable, ignoré, non spécifié, nous les remplaçons par ( non ICU)
## on suppose que les cas critiques qui était en soins intensifs ne peuxent pas être oublié.

array([2, 1], dtype=int64)

In [ ]:
corr = df.corr()
corr.style.background_gradient(cmap='coolwarm')


In [ ]:
## dans ce graphique de correlation nous distinguons deux types de correlations :
##positive et négative selon le type de variable


In [ ]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(df, test_size = 0.2, stratify = df['icu'], random_state = 44)
test.groupby('icu').size()
test.groupby('icu').size()

icu
1      2022
2    111299
dtype: int64

In [ ]:
# PART2 : correlation positive : 
## Variables_negative_corr_ x: contact_other_covid; age; patient_type

X_train = train[['pneumonia', 'intubed', 'covid_res','contact_other_covid', 'age', 'patient_type']]
y_train = train.icu
X_test = test[['pneumonia', 'intubed', 'covid_res','contact_other_covid', 'age', 'patient_type']]
y_test = test.icu


In [ ]:
X_test.shape, y_test.shape, X_train.shape, y_train.shape

((113321, 6), (113321,), (453281, 6), (453281,))

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler



pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)  # apply scaling on training data


pipe.score(X_test, y_test)  # apply scaling on testing data, without leaking training data.


0.9832246450349008

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
my_classifier = KNeighborsClassifier()

In [ ]:
my_classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
predictions = my_classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))

0.98224512667555


In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

print(classification_report(y_test, predictions))



              precision    recall  f1-score   support

           1       0.50      0.25      0.34      2022
           2       0.99      1.00      0.99    111299

    accuracy                           0.98    113321
   macro avg       0.75      0.62      0.66    113321
weighted avg       0.98      0.98      0.98    113321



In [ ]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes = (8,8,8), activation='tanh', max_iter=700)

In [ ]:
clf.fit(X_train, y_train)

MLPClassifier(activation='tanh', hidden_layer_sizes=(8, 8, 8), max_iter=700)

In [ ]:
## Prediction et performances sur les données d'entrainement 
predict_train = clf.predict(X_train)
accuracy_score(y_train, predict_train)

0.9826663813396105

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
predict_train = clf.predict(X_train)
print(confusion_matrix(y_train, predict_train))

[[  3736   4354]
 [  3503 441688]]


In [ ]:
predict_test = clf.predict(X_test)
print(confusion_matrix(y_test, predict_test))

[[   940   1082]
 [   898 110401]]


In [1]:
print(classification_report(y_train, predict_train))
print(classification_report(y_test, predict_test))

NameError: ignored